# Server configuration
server:
  port: 8081
  servlet:
    context-path: /bank
#http://localhost:8081/bank/v3/api-docs



# Application properties
spring:
  application:
    name: the-bank-project

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: thinhproee@gmail.com
    password: rmakdncnfplgdrfr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/tja_bank
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


# JWT
jwt:
  expiration: 3600 # seconds
  refreshable-duration: 3600
  secretKey: LLaTGzHHnTJRbK0+yVZq3ff/H+/JRmmoK2SCMaaJ5Eo=

